import type { User } from './types';

// Real roster for Chi hội sinh viên Trà Vinh — from business_data/users.md and roles.md.
// IDs u-bch-1, u-bch-cntt-2/3, and u-member-1..5 are kept stable (referenced by mock
// activities/forum/feedback/badges); the rest use new IDs.
export const users: User[] = [
  {
    id: 'u-admin',
    name: 'Quản Trị Viên',
    role: 'admin',
    subAssociationIds: [],
    email: 'admin@ctu.edu.vn',
    avatarInitials: 'QT',
    bio: 'Quản trị hệ thống toàn trường.',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-bch-1',
    name: 'Nguyễn Trần Phương Anh',
    role: 'bch',
    bchTitle: 'chi-hoi-truong',
    subAssociationIds: ['sa-tv'],
    email: 'anh.nguyen@ctu.edu.vn',
    avatarInitials: 'PA',
    bio: 'Chi hội trưởng Chi hội sinh viên Trà Vinh, nhiệm kỳ 2025–2026.',
    studentId: 'B2400031',
    major: 'Sư phạm Vật lý K50',
    isCoreMember: true,
    badgeIds: ['b-outstanding-oct', 'b-founder'],
  },
  {
    id: 'u-bch-cntt-2',
    name: 'Lê Hoàng Dửng',
    role: 'bch',
    bchTitle: 'chi-hoi-pho',
    subAssociationIds: ['sa-tv'],
    email: 'dung.le@ctu.edu.vn',
    avatarInitials: 'HD',
    bio: 'Chi hội phó Chi hội sinh viên Trà Vinh, nhiệm kỳ 2025–2026.',
    studentId: 'B2410052',
    major: 'Giáo dục Tiểu học K50',
    isCoreMember: true,
    badgeIds: [],
  },
  {
    id: 'u-bch-cntt-3',
    name: 'Lương Chí Tâm',
    role: 'bch',
    bchTitle: 'uy-vien-bch',
    subAssociationIds: ['sa-tv'],
    email: 'tam.luong@ctu.edu.vn',
    avatarInitials: 'CT',
    bio: 'Ủy viên Ban Chấp Hành Chi hội sinh viên Trà Vinh, nhiệm kỳ 2025–2026.',
    studentId: 'B2408110',
    major: 'Sư phạm Tin học K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-1',
    name: 'Nguyễn Ngọc Như Phúc',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'phuc.nguyen@student.ctu.edu.vn',
    avatarInitials: 'NP',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2206996',
    major: 'Giáo dục Tiểu học K48',
    isCoreMember: true,
    badgeIds: ['b-outstanding-oct'],
  },
  {
    id: 'u-member-2',
    name: 'Võ Thành Công',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'cong.vo@student.ctu.edu.vn',
    avatarInitials: 'TC',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2300033',
    major: 'Sư phạm Vật lý K49',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-3',
    name: 'Nguyễn Huỳnh Phương Pháp',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'phap.nguyen@student.ctu.edu.vn',
    avatarInitials: 'PP',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2405836',
    major: 'Sư phạm Khoa học tự nhiên K50',
    isCoreMember: false,
    badgeIds: ['b-volunteer-star'],
  },
  {
    id: 'u-member-4',
    name: 'Thi Quốc Bảo',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'bao.thi@student.ctu.edu.vn',
    avatarInitials: 'QB',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2407161',
    major: 'Kỹ thuật xây dựng K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-5',
    name: 'Chung Trần Nhật Thuận',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'thuan.chung@student.ctu.edu.vn',
    avatarInitials: 'NT',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2407867',
    major: 'Xã hội học K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-8',
    name: 'Phạm Đăng Khoa',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'khoa.pham@student.ctu.edu.vn',
    avatarInitials: 'DK',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2408628',
    major: 'Công nghệ kỹ thuật hóa học K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-9',
    name: 'Trần Nguyễn Linh Đan',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'dan.tran@student.ctu.edu.vn',
    avatarInitials: 'LD',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2410003',
    major: 'Giáo dục Tiểu học K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-10',
    name: 'Phạm Nguyễn Khánh Băng',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'bang.pham@student.ctu.edu.vn',
    avatarInitials: 'KB',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2410097',
    major: 'Giáo dục Công dân K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-11',
    name: 'Nguyễn Minh Thơ',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'tho.nguyen@student.ctu.edu.vn',
    avatarInitials: 'MT',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2410304',
    major: 'Quản lý tài nguyên và môi trường K50',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-12',
    name: 'Thái Ngọc Anh Thư',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'thu.thai@student.ctu.edu.vn',
    avatarInitials: 'AT',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2500072',
    major: 'Sư phạm Toán học K51',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-13',
    name: 'Trần Hoàng Như Ý',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'y.tran@student.ctu.edu.vn',
    avatarInitials: 'NY',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2504596',
    major: 'Toán ứng dụng K51',
    isCoreMember: false,
    badgeIds: [],
  },
  {
    id: 'u-member-14',
    name: 'Đỗ Nguyễn Bảo Nhi',
    role: 'member',
    subAssociationIds: ['sa-tv'],
    email: 'nhi.do@student.ctu.edu.vn',
    avatarInitials: 'BN',
    bio: 'Hội viên Chi hội sinh viên Trà Vinh.',
    studentId: 'B2510948',
    major: 'Giáo dục Tiểu học K51',
    isCoreMember: false,
    badgeIds: [],
  },
];

export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function getUsersBySubAssociation(subAssociationId: string): User[] {
  return users.filter((u) => u.subAssociationIds.includes(subAssociationId));
}
